imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@WMUserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: WM\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
        mailer: fos_user.mailer.twig_swift
#        mailer: app.custom_fos_user_mailer
    registration:
        confirmation:
            enabled: true
    from_email:
        address: kraj.jeremy@gmail.com
        sender_name: Cartesa
    resetting:
        email:
            template: WMUserBundle:Email:password_resseting.email.twig

#PUGXMultiUserBundle Configuration
pugx_multi_user:
  users:
    user_one:
        entity:
          class: WM\UserBundle\Entity\UserOne
#          factory:
        registration:
          form:
            type: WM\UserBundle\Form\Type\RegistrationUserOneFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: WMUserBundle:Registration:user_one.form.html.twig
        profile:
          form:
            type: WM\UserBundle\Form\Type\ProfileUserOneFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
          template: WMUserBundle:Profile:user_one.form.html.twig
    user_two:
        entity:
          class: WM\UserBundle\Entity\UserTwo
        registration:
          form:
            type: WM\UserBundle\Form\Type\RegistrationUserTwoFormType
          template: WMUserBundle:Registration:user_two.form.html.twig
        profile:
          form:
            type: WM\UserBundle\Form\Type\ProfileUserTwoFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
          template: WMUserBundle:Profile:user_two.form.html.twig





